//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string use_nombr { get; set; }
        public string use_apellido { get; set; }
        public Nullable<int> use_edad { get; set; }
        public string use_bajaLogica { get; set; }
        public string use_dni { get; set; }
    }
}
